version: "3.9"

services:
  web:
    build: .
    container_name: work-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb

  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres  # Имя пользователя
      POSTGRES_PASSWORD: password  # Пароль
      POSTGRES_DB: mydb  # Имя базы данных
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: